<?php
/********MIDDLE END**************
Project:  CS 490 - Group # 2    *
FileName: commandLine.php	    *
By:       Angelica Llerena		*
Date:     March 15, 2016.		*
*********************************/
session_start();

$info['command'] = $_POST["command"]; // sent post information
$cmd = $info['command'];

//CONSENT
if ($cmd ==1){include 'signUP.php';}				//DONE
elseif($cmd==2){include 'login.php';}				//DONE
elseif($cmd==15){include 'acceptFriendRequest.php';} //need testing (DONE)
//elseif($cmd==##){include 'rejectFriendRequest.php';} //need testing (DONE)



//CREATE...
elseif($cmd==3){include 'createEvent.php';}			//DONE
elseif($cmd==4){include 'createComment.php';}		//TO-DO....
elseif($cmd==7){include 'createFriendRequest.php';}	//need testing (DONE)

//UPDATES...
//elseif($cmd==##){include 'updateEventBio.php';}		//TO-DO....
//elseif($cmd==##){include 'updateEventEndDateTime.php';}		//TO-DO.....
//elseif($cmd==##){include 'updateEventLocation.php';}		//TO-DO.....
//elseif($cmd==##){include 'updateEventName.php';}		//TO-DO.....
//elseif($cmd==##){include 'updateEventStartDateTime.php';}		//TO-DO.....
elseif($cmd==5){include 'updateUserBio.php';}		//TO-DO....
//elseif($cmd==##){include 'updateUserEmail.php';}		//TO-DO.....
//elseif($cmd==##){include 'updateUserFirstname.php';}		//TO-DO.....
//elseif($cmd==##){include 'updateUserLastname.php';}		//TO-DO.....
//elseif($cmd==##){include 'updateUserPassword';}		//TO-DO.....
elseif($cmd==6){include 'updateUserTag.php';}		//TO-DO......
//elseif($cmd==##){include 'updateUserUsername.php';}		//TO-DO.....
elseif($cmd==10){include 'updateUserEvents.php';}	//TO-DO....



//REMOVE....
elseif($cmd==14){include 'removeUserTag.php';}		//TO-DO....
//elseif($cmd==##){include 'removeEventTag.php';}		//TO-DO....
//elseif($cmd==##){include 'removeUserEvent.php';}		//TO-DO....
//elseif($cmd==##){include 'removeUserTag.php';}		//TO-DO....
//elseif($cmd==##){include 'removeUserFriend.php';}		//TO-DO....



//RETURN...
elseif($cmd==8){include 'recommendEvents.php';}		//DONE
elseif($cmd==9){include 'displayUserInfo.php';}		//TO-DO....
elseif($cmd==16){include 'displayUsers.php';}		//DONE


//MIDDLE - ONLY
elseif($cmd==11){include 'displayTags.php';}		//DONE
elseif($cmd==12){include 'search.php';}				//DONE
elseif($cmd==13){include 'futureEventsWithFriends.php';}	//DONE
elseif($cmd==24){include 'displayEvents.php';}		//DONE
elseif($cmd==25){include 'futureEvents.php';}		//DONE
elseif($cmd==26){include 'userPastEvents.php';}		//TO-DO...
else{echo"Error: 404";}

?>
